[2023-05-07T22:22:13.174+0000] {processor.py:153} INFO - Started process (PID=9843) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:22:13.175+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:22:13.175+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:22:13.175+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:22:13.191+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:22:13.190+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:22:13.191+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:22:13.191+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:22:13.191+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:22:13.198+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-05-07T22:22:59.118+0000] {processor.py:153} INFO - Started process (PID=10178) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:22:59.119+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:22:59.120+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:22:59.120+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:22:59.135+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:22:59.135+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:22:59.135+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:22:59.135+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:22:59.135+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:22:59.143+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-05-07T22:23:39.773+0000] {processor.py:153} INFO - Started process (PID=10564) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:23:39.774+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:23:39.775+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:23:39.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:23:39.790+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:23:39.790+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:23:39.790+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:23:39.790+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:23:39.790+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:23:39.799+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-05-07T22:24:19.881+0000] {processor.py:153} INFO - Started process (PID=10867) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:24:19.882+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:24:19.882+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:24:19.882+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:24:19.899+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:24:19.899+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:24:19.900+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:24:19.899+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:24:19.900+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:24:19.907+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-05-07T22:25:07.013+0000] {processor.py:153} INFO - Started process (PID=11236) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:25:07.014+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:25:07.014+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:25:07.014+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:25:07.030+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:25:07.029+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:25:07.030+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:25:07.030+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:25:07.030+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:25:07.037+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-05-07T22:25:43.996+0000] {processor.py:153} INFO - Started process (PID=11519) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:25:43.997+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:25:43.997+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:25:43.997+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:25:44.013+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:25:44.012+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:25:44.013+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:25:44.013+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:25:44.013+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:25:44.021+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:26:25.989+0000] {processor.py:153} INFO - Started process (PID=11815) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:26:25.990+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:26:25.990+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:26:25.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:26:26.006+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:26:26.005+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:26:26.006+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:26:26.006+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:26:26.006+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:26:26.013+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-05-07T22:27:08.581+0000] {processor.py:153} INFO - Started process (PID=12104) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:27:08.582+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:27:08.583+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:27:08.582+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:27:08.598+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:27:08.597+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:27:08.598+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:27:08.598+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:27:08.598+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:27:08.605+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:27:51.132+0000] {processor.py:153} INFO - Started process (PID=12386) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:27:51.133+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:27:51.133+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:27:51.133+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:27:51.150+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:27:51.150+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:27:51.150+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:27:51.150+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:27:51.151+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:27:51.158+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-05-07T22:28:34.294+0000] {processor.py:153} INFO - Started process (PID=12689) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:28:34.295+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:28:34.296+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:28:34.296+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:28:34.317+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:28:34.317+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:28:34.317+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:28:34.317+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:28:34.317+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:28:34.326+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-05-07T22:29:12.533+0000] {processor.py:153} INFO - Started process (PID=12956) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:29:12.533+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:29:12.534+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:29:12.534+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:29:12.556+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:29:12.555+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:29:12.557+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:29:12.556+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:29:12.557+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:29:12.568+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2023-05-07T22:29:55.739+0000] {processor.py:153} INFO - Started process (PID=13253) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:29:55.740+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:29:55.740+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:29:55.740+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:29:55.756+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:29:55.756+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:29:55.756+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:29:55.756+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:29:55.756+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:29:55.764+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:30:35.722+0000] {processor.py:153} INFO - Started process (PID=13533) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:30:35.723+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:30:35.723+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:30:35.723+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:30:35.739+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:30:35.738+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:30:35.739+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:30:35.739+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:30:35.739+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:30:35.747+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:31:26.486+0000] {processor.py:153} INFO - Started process (PID=13869) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:31:26.487+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:31:26.488+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:31:26.487+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:31:26.504+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:31:26.503+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:31:26.504+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:31:26.504+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:31:26.504+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:31:26.511+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:32:11.197+0000] {processor.py:153} INFO - Started process (PID=14190) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:32:11.197+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:32:11.198+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:32:11.198+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:32:11.213+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:32:11.213+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:32:11.214+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:32:11.214+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:32:11.214+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:32:11.221+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-05-07T22:32:58.416+0000] {processor.py:153} INFO - Started process (PID=14515) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:32:58.417+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:32:58.418+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:32:58.418+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:32:58.434+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:32:58.433+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:32:58.434+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:32:58.434+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:32:58.434+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:32:58.443+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-05-07T22:33:48.363+0000] {processor.py:153} INFO - Started process (PID=14861) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:33:48.364+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:33:48.365+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:33:48.364+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:33:48.490+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:33:48.489+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:33:48.490+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:33:48.490+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:33:48.490+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:33:48.495+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.135 seconds
[2023-05-07T22:34:35.997+0000] {processor.py:153} INFO - Started process (PID=15255) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:34:35.998+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:34:35.998+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:34:35.998+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:34:36.014+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:34:36.013+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:34:36.014+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:34:36.014+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:34:36.014+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:34:36.022+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:35:13.287+0000] {processor.py:153} INFO - Started process (PID=15509) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:35:13.288+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:35:13.288+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:35:13.288+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:35:13.303+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:35:13.303+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:35:13.304+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:35:13.304+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:35:13.304+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:35:13.311+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-05-07T22:35:54.951+0000] {processor.py:153} INFO - Started process (PID=15805) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:35:54.951+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:35:54.952+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:35:54.952+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:35:54.981+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:35:54.981+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:35:54.982+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:35:54.982+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:35:54.982+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:35:55.028+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2023-05-07T22:36:39.248+0000] {processor.py:153} INFO - Started process (PID=16134) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:36:39.249+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:36:39.249+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:36:39.249+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:36:39.265+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:36:39.265+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:36:39.265+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:36:39.265+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:36:39.266+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:36:39.273+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:37:20.986+0000] {processor.py:153} INFO - Started process (PID=16426) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:37:20.987+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:37:20.987+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:37:20.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:37:21.003+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:37:21.002+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:37:21.003+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:37:21.003+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:37:21.003+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:37:21.017+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-05-07T22:38:03.431+0000] {processor.py:153} INFO - Started process (PID=16739) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:38:03.431+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:38:03.432+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:38:03.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:38:03.448+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:38:03.448+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:38:03.448+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:38:03.448+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:38:03.448+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:38:03.455+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:38:38.369+0000] {processor.py:153} INFO - Started process (PID=16985) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:38:38.370+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:38:38.370+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:38:38.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:38:38.387+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:38:38.386+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:38:38.387+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:38:38.387+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:38:38.387+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:38:38.395+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:39:21.361+0000] {processor.py:153} INFO - Started process (PID=17307) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:39:21.361+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:39:21.362+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:39:21.362+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:39:21.379+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:39:21.378+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:39:21.379+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:39:21.379+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:39:21.379+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:39:21.387+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-05-07T22:39:56.071+0000] {processor.py:153} INFO - Started process (PID=17557) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:39:56.072+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:39:56.072+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:39:56.072+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:39:56.087+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:39:56.087+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:39:56.088+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:39:56.088+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:39:56.088+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:39:56.095+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-05-07T22:40:35.339+0000] {processor.py:153} INFO - Started process (PID=17864) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:40:35.340+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:40:35.341+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:40:35.340+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:40:35.357+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:40:35.356+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:40:35.357+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:40:35.357+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:40:35.357+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:40:35.364+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:41:15.470+0000] {processor.py:153} INFO - Started process (PID=18152) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:41:15.470+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:41:15.471+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:41:15.471+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:41:15.486+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:41:15.486+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:41:15.486+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:41:15.486+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:41:15.487+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:41:15.494+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-05-07T22:41:56.499+0000] {processor.py:153} INFO - Started process (PID=18455) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:41:56.500+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:41:56.501+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:41:56.501+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:41:56.517+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:41:56.516+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:41:56.517+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:41:56.517+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:41:56.517+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:41:56.525+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-05-07T22:42:37.104+0000] {processor.py:153} INFO - Started process (PID=18831) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:42:37.104+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:42:37.105+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:42:37.105+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:42:37.121+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:42:37.120+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:42:37.121+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:42:37.121+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:42:37.121+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:42:37.128+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:43:11.183+0000] {processor.py:153} INFO - Started process (PID=19152) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:43:11.184+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:43:11.185+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:43:11.185+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:43:11.200+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:43:11.200+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:43:11.201+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:43:11.200+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:43:11.201+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:43:11.208+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-05-07T22:43:53.179+0000] {processor.py:153} INFO - Started process (PID=19618) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:43:53.179+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:43:53.180+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:43:53.180+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:43:53.195+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:43:53.195+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:43:53.196+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:43:53.195+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:43:53.196+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:43:53.203+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-05-07T22:44:34.738+0000] {processor.py:153} INFO - Started process (PID=20066) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:44:34.739+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:44:34.740+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:44:34.740+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:44:34.756+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:44:34.756+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:44:34.756+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:44:34.756+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:44:34.756+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:44:34.764+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-05-07T22:45:13.287+0000] {processor.py:153} INFO - Started process (PID=20362) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:45:13.288+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:45:13.289+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:45:13.288+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:45:13.304+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:45:13.304+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:45:13.305+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:45:13.305+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:45:13.305+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:45:13.313+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-05-07T22:45:49.793+0000] {processor.py:153} INFO - Started process (PID=20736) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:45:49.794+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:45:49.795+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:45:49.795+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:45:49.811+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:45:49.810+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:45:49.811+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:45:49.811+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:45:49.811+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:45:49.820+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-05-07T22:46:22.277+0000] {processor.py:153} INFO - Started process (PID=21104) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:46:22.277+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:46:22.278+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:46:22.278+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:46:22.293+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:46:22.293+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:46:22.294+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:46:22.293+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:46:22.294+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:46:22.302+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-05-07T22:47:01.686+0000] {processor.py:153} INFO - Started process (PID=21464) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:47:01.687+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:47:01.687+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:47:01.687+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:47:01.704+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:47:01.703+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:47:01.704+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:47:01.704+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:47:01.705+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:47:01.794+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.111 seconds
[2023-05-07T22:47:42.059+0000] {processor.py:153} INFO - Started process (PID=21750) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:47:42.059+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:47:42.060+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:47:42.060+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:47:42.076+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:47:42.075+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:47:42.076+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:47:42.076+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:47:42.076+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:47:42.083+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:48:25.291+0000] {processor.py:153} INFO - Started process (PID=22143) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:48:25.292+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:48:25.292+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:48:25.292+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:48:25.308+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:48:25.307+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:48:25.308+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:48:25.308+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:48:25.308+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:48:25.316+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:49:09.508+0000] {processor.py:153} INFO - Started process (PID=22607) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:49:09.509+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:49:09.509+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:49:09.509+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:49:09.525+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:49:09.524+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:49:09.525+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:49:09.525+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:49:09.525+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:49:09.532+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-05-07T22:49:43.634+0000] {processor.py:153} INFO - Started process (PID=22934) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:49:43.635+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:49:43.635+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:49:43.635+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:49:43.651+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:49:43.650+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:49:43.651+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:49:43.651+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:49:43.651+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:49:43.659+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:50:26.431+0000] {processor.py:153} INFO - Started process (PID=23249) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:50:26.432+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:50:26.432+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:50:26.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:50:26.448+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:50:26.448+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:50:26.448+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:50:26.448+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:50:26.449+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:50:26.457+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-05-07T22:51:10.127+0000] {processor.py:153} INFO - Started process (PID=23630) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:51:10.128+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:51:10.129+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:51:10.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:51:10.145+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:51:10.144+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:51:10.145+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:51:10.145+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:51:10.145+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:51:10.153+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:51:50.963+0000] {processor.py:153} INFO - Started process (PID=23912) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:51:50.963+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:51:50.964+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:51:50.964+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:51:50.980+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:51:50.979+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:51:50.980+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:51:50.980+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:51:50.980+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:51:50.987+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:52:34.536+0000] {processor.py:153} INFO - Started process (PID=24067) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:52:34.536+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:52:34.537+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:52:34.537+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:52:34.552+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:52:34.552+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:52:34.553+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:52:34.553+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:52:34.553+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:52:34.560+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:53:16.417+0000] {processor.py:153} INFO - Started process (PID=25099) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:53:16.418+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:53:16.419+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:53:16.419+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:53:16.434+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:53:16.434+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:53:16.435+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:53:16.435+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:53:16.435+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:53:16.442+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:53:50.816+0000] {processor.py:153} INFO - Started process (PID=25381) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:53:50.817+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:53:50.817+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:53:50.817+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:53:50.833+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:53:50.832+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:53:50.833+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:53:50.833+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:53:50.834+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:53:50.841+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:54:24.696+0000] {processor.py:153} INFO - Started process (PID=25645) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:54:24.697+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:54:24.697+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:54:24.697+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:54:24.713+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:54:24.713+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:54:24.713+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:54:24.713+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:54:24.714+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:54:24.721+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:55:04.986+0000] {processor.py:153} INFO - Started process (PID=25944) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:55:04.987+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:55:04.987+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:55:04.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:55:05.003+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:55:05.002+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:55:05.003+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:55:05.003+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:55:05.003+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:55:05.011+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-05-07T22:55:45.272+0000] {processor.py:153} INFO - Started process (PID=26228) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:55:45.273+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:55:45.275+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:55:45.275+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:55:45.290+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:55:45.290+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:55:45.291+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:55:45.290+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:55:45.291+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:55:45.298+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-05-07T22:56:18.511+0000] {processor.py:153} INFO - Started process (PID=26453) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:56:18.512+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:56:18.512+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:56:18.512+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:56:18.528+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:56:18.527+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:56:18.528+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:56:18.528+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:56:18.528+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:56:18.536+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:57:00.553+0000] {processor.py:153} INFO - Started process (PID=26737) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:57:00.554+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:57:00.555+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:57:00.554+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:57:00.571+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:57:00.570+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:57:00.571+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:57:00.571+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:57:00.571+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:57:00.578+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-05-07T22:57:42.227+0000] {processor.py:153} INFO - Started process (PID=27031) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:57:42.228+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-07T22:57:42.229+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:57:42.229+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:57:42.245+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:57:42.244+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-07T22:57:42.245+0000] {logging_mixin.py:137} INFO - [2023-05-07T22:57:42.245+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-07T22:57:42.245+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-07T22:57:42.252+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
